// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZsfOayw9NdXPXUD6wlfh4bwb0yfnWFc',
    appId: '1:356230225441:web:0c70037ae48fb585414d60',
    messagingSenderId: '356230225441',
    projectId: 'ivycollaborative-cebdc',
    authDomain: 'ivycollaborative-cebdc.firebaseapp.com',
    storageBucket: 'ivycollaborative-cebdc.appspot.com',
    measurementId: 'G-1BLB9XVMYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWAUcj2HT19Cpvu9rtqlXw74r60SOApzo',
    appId: '1:356230225441:android:00b75f48f8ac79e8414d60',
    messagingSenderId: '356230225441',
    projectId: 'ivycollaborative-cebdc',
    storageBucket: 'ivycollaborative-cebdc.appspot.com',
  );
}
